name: college_community
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  dartz: ^0.10.1
  hive: ^2.2.3
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  file_picker: ^9.0.2
  sensors_plus: ^6.1.1
  url_launcher: ^6.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  pretty_dio_logger: ^1.4.0
  flutter_launcher_icons: ^0.14.3
  mockito: ^5.4.4
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/appicon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400

    - family: Monstserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
  #
